name: hire_driver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  geocoding: ^4.0.0
  geolocator: ^14.0.2

  # OPENSTREETMAP
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  google_fonts: ^6.2.1
  country_code_picker: ^3.0.0
  image_picker: ^1.1.2

  http: ^1.2.1
  shared_preferences: ^2.2.2
  http_parser: ^4.1.2
  dio: ^5.9.2

  # RECEIPT DOWNLOAD
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10

  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg